FROM docker.elastic.co/elasticsearch/elasticsearch:8.15.0

# IK Analysis plugin for Chinese text segmentation (ik_max_word / ik_smart)
RUN elasticsearch-plugin install --batch https://get.infini.cloud/elasticsearch/analysis-ik/8.15.0
